language: android

sudo: false

android:
  components:
  - build-tools-24.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
before_install:
  - chmod +x gradlew
script:
  - "./gradlew assembleRelease"
