language: android

sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-android-m2repository
  - extra-android-support
before_install:
  - chmod +x gradlew
script:
  - "./gradlew assembleRelease"
